[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; --- N16R8 DONANIM AYARLARI ---
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB

; Ozel bolumleme tablomuzu kullaniyoruz
board_build.partitions = partitions.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    ; BadUSB (MSC ve HID) kullanabilmek icin TinyUSB stack aktif edilmeli
    -DARDUINO_USB_MODE=0 
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Eger Adafruit TinyUSB kullaniyorsan bunu da eklemen gerekebilir:
    ; -DUSE_TINYUSB=true 

; --- KÜTÜPHANELER ---
lib_deps = 
    h2zero/NimBLE-Arduino @ ^1.4.1